/**
 * The catalog's shape as pure data — no component imports, so consumers that
 * cannot process CSS-importing modules (the Playwright screenshot spec) can
 * still enumerate every cell. Hand-maintained on purpose and held to the
 * real catalog by a parity block in catalog.test.tsx: add a fixture without
 * updating this and the suite fails naming the entry.
 */
export interface ManifestEntry {
  fixtures: string[];
  dialog?: boolean;
}

export const catalogManifest: Record<string, ManifestEntry> = {
  "ask-note": {
    fixtures: [
      "answer",
      "answer-with-code",
      "conversation",
      "error",
      "idle",
      "long-answer",
      "markup-as-text",
      "overflow",
      "streaming",
      "thinking",
      "unicode",
    ],
  },
  avatar: {
    fixtures: [
      "cjk-name",
      "emoji-name",
      "empty-name",
      "image",
      "initials",
      "large",
      "rtl-name",
      "silent",
      "single-name",
      "whitespace-name",
    ],
  },
  badge: {
    fixtures: [
      "accent",
      "danger",
      "default",
      "markup-as-text",
      "muted",
      "overflow",
      "success",
      "warning",
    ],
  },
  button: {
    fixtures: [
      "busy",
      "combo",
      "danger",
      "disabled",
      "ghost",
      "markup-as-text",
      "overflow",
      "primary",
      "quiet",
    ],
  },
  "ci-pill": {
    fixtures: [
      "failure",
      "failure-overflow",
      "missing",
      "none",
      "pending",
      "single-check",
      "success",
    ],
  },
  "code-cell": {
    fixtures: [
      "empty",
      "indent-guides",
      "markup-as-text",
      "overflow",
      "raw-markup",
      "tabs",
      "typical",
      "unicode",
      "whitespace",
    ],
  },
  "comment-tools": {
    fixtures: [
      "chord",
      "copy-only",
      "delete-only",
      "edit-only",
      "markup-body",
      "own",
      "own-with-kbd",
      "unknown-key",
    ],
  },
  "find-bar": {
    fixtures: [
      "case-sensitive",
      "closed",
      "count-4-digit",
      "empty-query",
      "markup-as-text",
      "no-matches",
      "one-match",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  "help-overlay": {
    dialog: true,
    fixtures: [
      "empty",
      "full",
      "long-chord",
      "markup-as-text",
      "one-section",
      "overflow",
      "unicode",
    ],
  },
  "highlight-indices": {
    fixtures: ["cjk", "empty-text", "every", "none", "out-of-range", "typical"],
  },
  "image-diff": {
    fixtures: [
      "added-only",
      "both-sides",
      "broken",
      "deleted-only",
      "loading",
      "markup-as-text",
      "no-source",
      "overflow",
      "tall",
      "tiny",
      "wide",
    ],
  },
  "issue-tracker-dialog": {
    dialog: true,
    fixtures: [
      "configured",
      "id-template",
      "invalid",
      "markup-as-text",
      "overflow",
      "unicode",
      "unset",
      "unsupported-scheme",
    ],
  },
  kbd: {
    fixtures: [
      "chord",
      "combo",
      "empty-string",
      "missing",
      "named",
      "single",
      "unknown-word",
    ],
  },
  markdown: {
    fixtures: [
      "blockquote",
      "code-fence",
      "emoji",
      "empty",
      "headings",
      "image",
      "image-slot",
      "inline-code",
      "link",
      "lists",
      "overflow",
      "raw-html",
      "rule",
      "sanitize-img-onerror",
      "sanitize-javascript-href",
      "sanitize-script",
      "suggestion",
      "suggestion-overflow",
      "suggestion-repeated-lines",
      "table",
      "task-list",
      "typical",
      "unicode",
    ],
  },
  "overview-ruler": {
    fixtures: [
      "all-unmeasured",
      "crowd-500",
      "current-out-of-range",
      "edges",
      "empty",
      "occurrence",
      "single",
      "typical",
      "unmeasured",
    ],
  },
  "pr-list-item": {
    fixtures: [
      "ancient",
      "cjk",
      "draft",
      "future",
      "huge-counts",
      "markup-as-text",
      "merged",
      "minimal",
      "no-avatar",
      "overflow",
      "read",
      "rtl",
      "selected",
      "unread",
      "zero-counts",
    ],
  },
  "purchase-prompt": {
    fixtures: [
      "already-licensed",
      "error",
      "overflow",
      "trial-active",
      "trial-expired",
      "unknown-status",
      "waiting",
    ],
  },
  "release-history": {
    dialog: true,
    fixtures: [
      "crowd-24",
      "empty",
      "failed",
      "loading",
      "markdown",
      "no-notes",
      "overflow",
      "single",
      "unicode",
    ],
  },
  "review-screen-pending": {
    fixtures: [
      "cached",
      "cold",
      "error",
      "error-overflow",
      "overflow",
      "unicode",
    ],
  },
  "review-verdicts": {
    fixtures: [
      "crowd-12",
      "empty",
      "markup-as-text",
      "mixed",
      "no-avatar",
      "one-approval",
      "overflow",
      "unicode",
    ],
  },
  "search-pane": {
    dialog: true,
    fixtures: [
      "badges",
      "crowd-200",
      "empty",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  spinner: {
    fixtures: ["bare", "labelled", "overflow"],
  },
  "ticket-title": {
    fixtures: [
      "id-template",
      "markup-as-text",
      "multiple-tickets",
      "near-miss",
      "no-ticket",
      "no-tracker",
      "one-ticket",
      "overflow",
      "repeated-separator",
      "trailing-slash",
      "unicode",
    ],
  },
  tooltip: {
    fixtures: [
      "anchored",
      "combo",
      "markup-as-text",
      "overflow",
      "rtl",
      "short",
    ],
  },
  "update-prompt": {
    fixtures: [
      "error",
      "ineligible",
      "ineligible-purchasing",
      "installing",
      "overflow",
      "ready-to-restart",
      "with-notes",
    ],
  },
  "whats-new": {
    fixtures: [
      "markup-as-text",
      "no-notes",
      "one-note",
      "overflow",
      "overflow-version",
      "unicode",
    ],
  },
};
