/**
 * The catalog's shape as pure data — no component imports, so consumers that
 * cannot process CSS-importing modules (the Playwright screenshot spec) can
 * still enumerate every cell. Hand-maintained on purpose and held to the
 * real catalog by a parity block in catalog.test.tsx: add a fixture without
 * updating this and the suite fails naming the entry.
 */
export interface ManifestEntry {
  fixtures: string[];
  dialog?: boolean;
}

export const catalogManifest: Record<string, ManifestEntry> = {
  "add-comment-box": {
    fixtures: [
      "draft-with-text",
      "empty-draft",
      "long-draft",
      "now-mode",
      "overflow",
      "raw-html",
      "reply",
      "submitting",
      "suggestion",
      "two-modes",
      "unicode",
    ],
  },
  "ai-model-combobox": {
    fixtures: [
      "closed",
      "crowd-120",
      "filtered",
      "free-text",
      "loading",
      "markup-as-text",
      "open-typical",
      "overflow",
      "unicode",
    ],
  },
  "ai-setup-dialog": {
    dialog: true,
    fixtures: [
      "crowd-120",
      "loading-models",
      "markup-as-text",
      "no-models",
      "overflow",
      "removing",
      "replacing-key",
      "saved-key",
      "saving",
      "unconfigured",
      "unicode",
      "unreachable",
      "validation-error",
    ],
  },
  "ask-note": {
    fixtures: [
      "answer",
      "answer-with-code",
      "conversation",
      "error",
      "idle",
      "long-answer",
      "markup-as-text",
      "overflow",
      "streaming",
      "thinking",
      "unicode",
    ],
  },
  avatar: {
    fixtures: [
      "cjk-name",
      "emoji-name",
      "empty-name",
      "image",
      "initials",
      "large",
      "rtl-name",
      "silent",
      "single-name",
      "whitespace-name",
    ],
  },
  badge: {
    fixtures: [
      "accent",
      "danger",
      "default",
      "dot",
      "dot-overflow",
      "markup-as-text",
      "muted",
      "overflow",
      "success",
      "warning",
    ],
  },
  button: {
    fixtures: [
      "busy",
      "combo",
      "danger",
      "disabled",
      "ghost",
      "markup-as-text",
      "overflow",
      "primary",
      "quiet",
    ],
  },
  "canned-comments-dialog": {
    dialog: true,
    fixtures: [
      "empty",
      "many",
      "markup-as-text",
      "minimal",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  "canned-suggestions": {
    fixtures: [
      "described-items",
      "empty",
      "full",
      "markup-as-text",
      "minimal",
      "overflow",
      "query-nearly-whole-line",
      "second-selected",
      "typical",
      "unicode",
    ],
  },
  "chat-composer": {
    fixtures: [
      "draft-with-chips",
      "draft-with-pasted-code",
      "overflow",
      "reply",
      "typical",
      "unicode",
    ],
  },
  "chat-panel": {
    fixtures: [
      "composer-draft",
      "inline-parts",
      "empty",
      "error",
      "fence-mid-stream",
      "markup-as-text",
      "overflow",
      "model-picker",
      "partial-10k",
      "pasted-and-note",
      "staged",
      "skill-chip",
      "slash-suggestions",
      "thinking",
      "threads",
      "trail-open",
      "tool-activity",
      "typical",
      "unicode",
    ],
  },
  "ci-checks": {
    fixtures: [
      "all-green",
      "empty",
      "missing",
      "mixed",
      "overflow",
      "single-pipeline",
      "unlinked",
    ],
  },
  "ci-pill": {
    fixtures: [
      "failure",
      "failure-overflow",
      "missing",
      "none",
      "pending",
      "single-check",
      "success",
    ],
  },
  "code-cell": {
    fixtures: [
      "empty",
      "indent-guides",
      "markup-as-text",
      "overflow",
      "raw-markup",
      "tabs",
      "typical",
      "unicode",
      "whitespace",
    ],
  },
  "command-palette": {
    dialog: true,
    fixtures: [
      "crowd-140",
      "empty",
      "full",
      "markup-as-text",
      "matches-many",
      "no-hints",
      "no-matches",
      "overflow",
      "overflow-query",
      "single",
      "unicode",
    ],
  },
  "comment-item": {
    fixtures: [
      "author-overflow",
      "body-overflow",
      "cjk",
      "code-fence",
      "empty-body",
      "image-only",
      "long",
      "markup-as-text",
      "no-timestamp",
      "no-tools",
      "own",
      "reply",
      "rtl",
      "suggestion",
      "typical",
    ],
  },
  "comment-thread": {
    fixtures: [
      "crowd",
      "long-chain",
      "not-resolvable",
      "overflow",
      "own-buried",
      "own-last",
      "resolved-folded",
      "single",
      "unicode",
    ],
  },
  "comment-tools": {
    fixtures: [
      "chord",
      "copy-only",
      "delete-only",
      "edit-only",
      "markup-body",
      "own",
      "own-with-kbd",
      "unknown-key",
    ],
  },
  "composer-editor": {
    fixtures: [
      "empty",
      "long-draft",
      "markdown",
      "minimal",
      "overflow",
      "placeholder-long",
      "plain-text",
      "raw-html",
      "suggestion",
      "unicode",
    ],
  },
  "diff-row": {
    fixtures: [
      "blank",
      "find-current",
      "flash",
      "huge-line-numbers",
      "indent-guides",
      "intraline",
      "markup-as-text",
      "occurrence",
      "overflow",
      "run-100",
      "run-20",
      "run-50",
      "run-context",
      "run-hunk-sandwich",
      "run-nesting",
      "run-replacement",
      "run-threaded",
      "run-wrapped",
      "selected",
      "synthetic",
      "tabs",
      "threaded",
      "unicode",
    ],
  },
  "file-section-header": {
    fixtures: [
      "added",
      "copied",
      "crowd",
      "expanded",
      "expanding",
      "markup-as-text",
      "minimal",
      "no-extension",
      "no-viewed-control",
      "overflow",
      "removed",
      "renamed",
      "root",
      "unicode",
      "unknown-status",
      "updated",
      "viewed",
    ],
  },
  "file-sidebar": {
    fixtures: [
      "collapsed",
      "crowd-300",
      "deep",
      "empty",
      "every-status",
      "flat",
      "none-viewed",
      "overflow",
      "single",
      "typical",
      "unicode",
      "viewed-all",
    ],
  },
  "file-status-glyph": {
    fixtures: [
      "added",
      "copied",
      "empty-status",
      "modified",
      "removed",
      "renamed",
      "unknown-status",
    ],
  },
  "find-bar": {
    fixtures: [
      "case-sensitive",
      "closed",
      "count-4-digit",
      "empty-query",
      "markup-as-text",
      "no-matches",
      "one-match",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  "help-overlay": {
    dialog: true,
    fixtures: [
      "empty",
      "filtered",
      "full",
      "long-chord",
      "markup-as-text",
      "no-matches",
      "one-section",
      "overflow",
      "unicode",
    ],
  },
  "highlight-indices": {
    fixtures: ["cjk", "empty-text", "every", "none", "out-of-range", "typical"],
  },
  "hunk-row": {
    fixtures: [
      "collapsed",
      "empty",
      "markup-as-text",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  "image-diff": {
    fixtures: [
      "added-only",
      "both-sides",
      "broken",
      "deleted-only",
      "loading",
      "markup-as-text",
      "no-source",
      "overflow",
      "tall",
      "tiny",
      "wide",
    ],
  },
  "inbox-detail": {
    fixtures: [
      "archived",
      "cjk",
      "draft",
      "last-comment",
      "markup-as-text",
      "minimal",
      "overflow",
      "rtl",
      "ticket",
      "typical",
      "zero-stats",
    ],
  },
  "inbox-tabs": {
    fixtures: [
      "archived-open",
      "cjk",
      "empty",
      "full",
      "huge-counts",
      "markup-as-text",
      "no-match",
      "overflow",
      "rtl",
      "single",
      "zero-count",
    ],
  },
  "inbox-zero": {
    fixtures: [
      "all-clear",
      "archived",
      "cjk",
      "empty",
      "markup-as-text",
      "overflow",
      "rtl",
      "with-action",
    ],
  },
  "issue-tracker-dialog": {
    dialog: true,
    fixtures: [
      "configured",
      "id-template",
      "invalid",
      "markup-as-text",
      "overflow",
      "unicode",
      "unset",
      "unsupported-scheme",
    ],
  },
  kbd: {
    fixtures: [
      "chord",
      "combo",
      "empty-string",
      "missing",
      "named",
      "single",
      "unknown-word",
    ],
  },
  markdown: {
    fixtures: [
      "blockquote",
      "code-fence",
      "emoji",
      "empty",
      "headings",
      "image",
      "image-slot",
      "inline-code",
      "link",
      "lists",
      "overflow",
      "raw-html",
      "rule",
      "sanitize-img-onerror",
      "sanitize-javascript-href",
      "sanitize-script",
      "suggestion",
      "suggestion-overflow",
      "suggestion-repeated-lines",
      "table",
      "task-list",
      "typical",
      "unicode",
    ],
  },
  "model-picker": {
    fixtures: [
      "crowd",
      "empty",
      "loading",
      "overflow",
      "typical",
      "unicode",
      "with-effort",
    ],
  },
  "notification-center": {
    dialog: true,
    fixtures: [
      "all-off",
      "all-read",
      "cjk",
      "empty",
      "markup-as-text",
      "no-avatar",
      "os-only",
      "overflow",
      "rtl",
      "scrolling",
      "typical",
    ],
  },
  "overview-ruler": {
    fixtures: [
      "all-unmeasured",
      "crowd-500",
      "current-out-of-range",
      "edges",
      "empty",
      "occurrence",
      "single",
      "typical",
      "unmeasured",
    ],
  },
  "pr-drawer": {
    fixtures: [
      "ci-failing",
      "crowd",
      "draft-present",
      "empty-conversation",
      "foreign-comment",
      "markup-as-text",
      "no-verdicts",
      "overflow",
      "own-comment",
      "typical",
      "unicode",
    ],
  },
  "pr-list-item": {
    fixtures: [
      "ancient",
      "cjk",
      "draft",
      "future",
      "huge-counts",
      "markup-as-text",
      "merged",
      "minimal",
      "no-avatar",
      "overflow",
      "read",
      "rtl",
      "selected",
      "unread",
      "zero-counts",
    ],
  },
  "pr-search": {
    dialog: true,
    fixtures: [
      "crowd-60",
      "files-crowd",
      "files-empty-query",
      "files-matches",
      "files-no-matches",
      "markup-as-text",
      "overflow-long-hit",
      "overflow-long-line",
      "overflow-unbreakable-query",
      "text-empty-query",
      "text-first-line",
      "text-hunk-boundary",
      "text-last-line",
      "text-no-matches",
      "text-snippets",
      "unicode",
    ],
  },
  "pr-summary": {
    fixtures: [
      "ancient",
      "ci-failing",
      "ci-none",
      "huge-diff",
      "just-now",
      "markup-as-text",
      "no-date",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  "purchase-prompt": {
    fixtures: [
      "already-licensed",
      "error",
      "overflow",
      "trial-active",
      "trial-expired",
      "unknown-status",
      "waiting",
    ],
  },
  "release-history": {
    dialog: true,
    fixtures: [
      "crowd-24",
      "empty",
      "failed",
      "loading",
      "markdown",
      "no-notes",
      "overflow",
      "single",
      "unicode",
    ],
  },
  "review-header": {
    fixtures: [
      "ci-failure",
      "ci-none",
      "ci-unknown",
      "everything",
      "huge-counts",
      "markup-as-text",
      "merged",
      "minimal",
      "overflow",
      "stacked",
      "unicode",
      "unknown-state",
    ],
  },
  "review-screen-pending": {
    fixtures: [
      "cached",
      "cold",
      "error",
      "error-overflow",
      "overflow",
      "unicode",
    ],
  },
  "review-toast": {
    fixtures: [
      "cjk",
      "huge-number",
      "markup-as-text",
      "minimal",
      "no-avatar",
      "one-more",
      "overflow",
      "reply",
      "reply-many",
      "reply-one-more",
      "rtl",
      "typical",
    ],
  },
  "review-verdicts": {
    fixtures: [
      "crowd-12",
      "empty",
      "markup-as-text",
      "mixed",
      "no-avatar",
      "one-approval",
      "overflow",
      "unicode",
    ],
  },
  "right-dock": {
    fixtures: [
      "chat-active",
      "indicators",
      "overflow",
      "single-tab",
      "two-tabs",
      "unicode",
    ],
  },
  "search-pane": {
    dialog: true,
    fixtures: [
      "badges",
      "crowd-200",
      "empty",
      "overflow",
      "typical",
      "unicode",
    ],
  },
  spinner: {
    fixtures: ["bare", "labelled", "overflow"],
  },
  "submit-review-modal": {
    dialog: true,
    fixtures: [
      "approve",
      "busy",
      "comment",
      "error",
      "long-body",
      "markup-as-text",
      "overflow",
      "own-pr",
      "pending-many",
      "pending-one",
      "request-changes",
      "unicode",
    ],
  },
  "thread-index": {
    fixtures: [
      "crowd-40",
      "empty",
      "markup-as-text",
      "newline-snippet",
      "outdated",
      "overflow",
      "resolved",
      "single",
      "typical",
      "unicode",
    ],
  },
  "ticket-title": {
    fixtures: [
      "id-template",
      "markup-as-text",
      "multiple-tickets",
      "near-miss",
      "no-ticket",
      "no-tracker",
      "one-ticket",
      "overflow",
      "repeated-separator",
      "trailing-slash",
      "unicode",
    ],
  },
  "token-gate": {
    fixtures: [
      "add-account",
      "auth-error",
      "error-overflow",
      "instances",
      "markup-as-text",
      "needs-setup",
      "self-hosted",
      "self-hosted-probed",
      "self-hosted-probing",
      "signed-out",
      "signing-in",
      "token-gitlab",
      "token-rejected",
      "unicode",
      "verifying-token",
    ],
  },
  tooltip: {
    fixtures: [
      "anchored",
      "combo",
      "markup-as-text",
      "overflow",
      "rtl",
      "short",
    ],
  },
  "update-prompt": {
    fixtures: [
      "error",
      "ineligible",
      "ineligible-purchasing",
      "installing",
      "overflow",
      "packaged",
      "packaged-ineligible",
      "ready-to-restart",
      "with-notes",
    ],
  },
  "watch-repos-dialog": {
    dialog: true,
    fixtures: [
      "crowd-60",
      "crowd-60-hits",
      "empty",
      "failed",
      "loading",
      "markup-as-text",
      "no-matches",
      "no-matches-plain",
      "overflow",
      "saving",
      "search-results",
      "searching",
      "single",
      "unicode",
      "write-failed",
    ],
  },
  "whats-new": {
    fixtures: [
      "markup-as-text",
      "no-notes",
      "one-note",
      "overflow",
      "overflow-version",
      "unicode",
    ],
  },
};
